### ISSUE TITLE
bootstrap.php.cache missing?

### ISSUE THREAD

**Issue by DorianVasco** [tsteur/open-source-tag-manager#1]
I tried to install like described on the seventag site, but I get some error:

`PHP Fatal error:  require_once(): Failed opening required '/var/customers/webs/XXXX/seventag/web/../var/bootstrap.php.cache' (include_path='.:/usr/share/php:/usr/share/pear') in /var/customers/webs/XXXX/seventag/web/install.php on line 22
`

**Comment by tsteur** [comment]
There was no such file in the archive. I presume it has to be generated somehow. I tried to quickly install it recently as well but had same problem I think. I have never actually used or installed it so far. Only had the downloaded archive while it was still OS

**Comment by DorianVasco** [comment]
yep, I started with a
`curl -S https://getcomposer.org/installer | php`
`php composer.phar update`
and finally changing two lines in composer.json:
41:        "guzzlehttp/guzzle": "*",
67        "satooshi/php-coveralls": "*"

It seems to work now

**Comment by tsteur** [comment]
Awesome, if you could update the installation description that would be amazing and helpful to get this project started again :)

**Comment by DorianVasco** [comment]
Well, there are more things to fix.. I'll have a look the next days and share my results. Regards, Dorian

**Comment by tsteur** [comment]
Awesome 👍

**Comment by DorianVasco** [comment]
Ok, I finally got it by following the advanced instructions to build the project. This routine creates all the necessary files and settings. Cheers

**Comment by tsteur** [comment]
Be awesome if you could share them with us by create A PR or a comment here or maybe you can point to a link? This will make it easier for other people.

**Comment by DorianVasco** [comment]
Well, I followed the instructions from https://github.com/tsteur/open-source-tag-manager/blob/master/doc/INSTALLATION.md
I will try it again, to confirm it is working (without my former tweaking).

Kind regards, Dorian

**Comment by gdubicki** [comment]
Hey @DorianVasco , so did you really get it working?

**Comment by DorianVasco** [comment]
@gdubicki Hi, unfortunatly not completely, but I did not find some spare time to figure it out.
The installation was successful, but the interface has still some errors.
